apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: scaling-ltd-tls
spec:
  secretName: scaling-ltd
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: scaling.ltd
  dnsNames:
    - scaling.ltd
    - www.scaling.ltd
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - scaling.ltd
          - www.scaling.ltd